### PR TITLE
Added sp, fr and sv

### PR DESCRIPTION
**Pull request by Sopor**

### CODE REVIEW

**Comment by vlmaksime** [comment]
Did You test it on your Kodi?
According [Gismeteo API](https://www.gismeteo.com/api/), it's support only this languages:

ru | (by default)
-- | --
en | english
ua | ukrainian
lt | lithuanian
lv | latvian
pl | polish
ro | romanian

**Comment by Sopor** [comment]
> Did You test it on your Kodi?
> According [Gismeteo API](https://www.gismeteo.com/api/), it's support only this languages:
> 
> ru	(by default)
> en	english
> ua	ukrainian
> lt	lithuanian
> lv	latvian
> pl	polish
> ro	romanian

No, i haven't tested it. Why is [German](https://github.com/vlmaksime/weather.gismeteo/blob/c154847155e4faaca1f5b2e19c58b01f801a7208/weather.gismeteo/resources/libs/__init__.py#L76) added if that doesn't work?

**Comment by vlmaksime** [comment]
German is not listed in the API, but for Germany there is available website [https://www.gismeteo.de](https://www.gismeteo.de). Therefore, this language is available in the API.
But Gismeteo doesn't have sites in Spanish, French, or Swedish. If you pass these parameters to the API, the answer will be returned in Russian.

**Comment by Sopor** [comment]
I see. Thanks for explaining for me and sorry if i bother you with useless PR's ... :)

**Pull request closed without merging**
